### ISSUE TITLE
Ash Console Auth Login on AWS

### ISSUE THREAD

**Issue by mtgnoah** [AshAvalanche/ash-rs#74]
This error below occured after running ```ash console auth login```
```Error storing access token: Platform secure storage failure: no secret service provider or dbus session found```

I was able to enter the code into the website to login for console and then when I went back to the CLI I had an error. I believe this error is related to the keyring. [https://github.com/keepassxreboot/keepassxc/issues/6274](url)

**Comment by Nuttymoon** [comment]
I was able to reproduce the issue when running the command from inside an EC2 instance (Ubuntu 22.04).

It's need related to keyring and the same error will happen on any device where keyring is not available. I will add a fallback to storing the OAuth tokens in plain text in this case.

**Comment by Nuttymoon** [comment]
This should be solved in [v0.4.0-alpha.3](https://github.com/AshAvalanche/ash-rs/releases/tag/v0.4.0-alpha.3).

Feel free to re-open if needed.
